[workspace]
members = [
  "ec-gpu",
  "ec-gpu-gen"
]

[patch.crates-io]
ec-gpu = { git = "https://github.com/filecoin-project/ec-gpu", branch = "vmx-64gib-debug" }
funty = { git = "https://github.com/bitvecto-rs/funty", rev = "7ef0d890fbcd8b3def1635ac1a877fc298488446" }
